version: 2.1

jobs:
  semgrep-scan:
    parameters: 

    environment:
      # Scan changed files in PRs, block on new issues only (existing issues ignored)
      # SEMGREP_BASELINE_REF: << parameters.diff_branch >>
      SEMGREP_REPO_URL: https://semgrep.dev/orgs/h4ckw1thn33r4j/
      SEMGREP_APP_TOKEN: 1ec1862ab329dd2a9d111366f6686c3770d3194c88a09cd5e37e533acb1f7bfd
      

      # Change job timeout (default is 1800 seconds; set to 0 to disable)
      # SEMGREP_TIMEOUT: 300

    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: "Semgrep scan"
          command: semgrep ci
workflows:
  Semgrep:
    jobs:
      - semgrep-scan